apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voter-app-pod
        app: demo-voting-app
  template:
    metadata:
      name: pankaj-voter-pod
      labels:
        name: voter-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voter-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80